spring:
  application:
    name: incidenthub-worker

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

incidenthub:
  worker:
    id: local-worker-1
    batch-size: 10
    poll-delay-ms: 5000
  alerts:
    batch-size: 10
    poll-delay-ms: 5000