spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/incidenthub
    username: incidenthub
    password: incidenthub

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true