spring:
  application:
    name: demo-payment-service

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info

incidenthub:
  api:
    base-url: http://localhost:8080

demo-payment:
  environment: local