import { useEffect, useMemo, useState } from 'react'
import { getAlerts, getIncidents } from '../api/incidenthubClient'
import { StatusBadge } from '../components/StatusBadge'
import type { Incident, IncidentAlert } from '../types/incidenthub'

type AlertsPageProps = {
  onSelectIncident: (incident: Incident) => void
}

type AlertStatusFilter = 'ALL' | string
type AlertChannelFilter = 'ALL' | string

function formatDate(value: string | null | undefined): string {
  if (!value) {
    return '—'
  }

  return new Intl.DateTimeFormat('en-US', {
    dateStyle: 'medium',
    timeStyle: 'medium',
  }).format(new Date(value))
}

function getUniqueValues(values: string[]): string[] {
  return Array.from(new Set(values)).sort()
}

function getIncidentSummary(incident: Incident | undefined): string {
  if (!incident) {
    return 'Incident not loaded'
  }

  return incident.summary
}

export function AlertsPage({ onSelectIncident }: AlertsPageProps) {
  const [alerts, setAlerts] = useState<IncidentAlert[]>([])
  const [incidents, setIncidents] = useState<Incident[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [statusFilter, setStatusFilter] = useState<AlertStatusFilter>('ALL')
  const [channelFilter, setChannelFilter] = useState<AlertChannelFilter>('ALL')
  const [search, setSearch] = useState('')

  useEffect(() => {
    async function loadAlerts() {
      try {
        setLoading(true)
        setError(null)

        const [alertsResponse, incidentsResponse] = await Promise.all([
          getAlerts(100),
          getIncidents(100),
        ])

        setAlerts(alertsResponse)
        setIncidents(incidentsResponse)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unexpected alerts loading error')
      } finally {
        setLoading(false)
      }
    }

    void loadAlerts()
  }, [])

  const incidentById = useMemo(() => {
    return incidents.reduce<Record<string, Incident>>((accumulator, incident) => {
      return {
        ...accumulator,
        [incident.incidentId]: incident,
      }
    }, {})
  }, [incidents])

  const statuses = useMemo(
    () => getUniqueValues(alerts.map((alert) => alert.status)),
    [alerts],
  )

  const channels = useMemo(
    () => getUniqueValues(alerts.map((alert) => alert.channel)),
    [alerts],
  )

  const filteredAlerts = useMemo(() => {
    const normalizedSearch = search.trim().toLowerCase()

    return alerts.filter((alert) => {
      const incident = incidentById[alert.incidentId]

      const matchesStatus = statusFilter === 'ALL' || alert.status === statusFilter
      const matchesChannel = channelFilter === 'ALL' || alert.channel === channelFilter

      const matchesSearch =
        normalizedSearch.length === 0 ||
        alert.title.toLowerCase().includes(normalizedSearch) ||
        alert.message.toLowerCase().includes(normalizedSearch) ||
        alert.channel.toLowerCase().includes(normalizedSearch) ||
        alert.status.toLowerCase().includes(normalizedSearch) ||
        incident?.summary.toLowerCase().includes(normalizedSearch) ||
        incident?.serviceName.toLowerCase().includes(normalizedSearch) ||
        incident?.environment.toLowerCase().includes(normalizedSearch)

      return matchesStatus && matchesChannel && matchesSearch
    })
  }, [alerts, channelFilter, incidentById, search, statusFilter])

  const sentCount = alerts.filter((alert) => alert.status === 'SENT').length
  const pendingCount = alerts.filter((alert) => alert.status === 'PENDING').length
  const failedCount = alerts.filter((alert) => alert.status === 'FAILED').length

  if (loading) {
    return (
      <div className="alerts-page">
        <div className="empty-state">
          <strong>Loading alerts...</strong>
          <span>Fetching alert delivery records from the IncidentHub API.</span>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="alerts-page">
        <div className="empty-state empty-state--error">
          <strong>Unable to load alerts</strong>
          <span>{error}</span>
        </div>
      </div>
    )
  }

  return (
    <div className="alerts-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">Operational notifications</p>
          <h1>Alerts</h1>
          <p>
            Review alert delivery attempts, channels, statuses and related incidents generated by
            IncidentHub operational workflows.
          </p>
        </div>

        <div className="page-header__status alerts-summary-card">
          <span>Total alerts</span>
          <strong>{alerts.length}</strong>
        </div>
      </header>

      <section className="alerts-kpi-grid">
        <article className="compact-kpi">
          <span>Sent</span>
          <strong>{sentCount}</strong>
          <StatusBadge value="SENT" variant="slo" />
        </article>

        <article className="compact-kpi">
          <span>Pending</span>
          <strong>{pendingCount}</strong>
          <StatusBadge value="PENDING" variant="slo" />
        </article>

        <article className="compact-kpi">
          <span>Failed</span>
          <strong>{failedCount}</strong>
          <StatusBadge value="FAILED" variant="slo" />
        </article>

        <article className="compact-kpi">
          <span>Filtered results</span>
          <strong>{filteredAlerts.length}</strong>
          <small>matching current filters</small>
        </article>
      </section>

      <section className="filters-card alerts-filters-card">
        <div className="filter-field filter-field--search">
          <label htmlFor="alert-search">Search</label>
          <input
            id="alert-search"
            placeholder="Search by title, message, channel, service or environment"
            type="search"
            value={search}
            onChange={(event) => setSearch(event.target.value)}
          />
        </div>

        <div className="filter-field">
          <label htmlFor="alert-status-filter">Status</label>
          <select
            id="alert-status-filter"
            value={statusFilter}
            onChange={(event) => setStatusFilter(event.target.value)}
          >
            <option value="ALL">All statuses</option>
            {statuses.map((status) => (
              <option key={status} value={status}>
                {status}
              </option>
            ))}
          </select>
        </div>

        <div className="filter-field">
          <label htmlFor="alert-channel-filter">Channel</label>
          <select
            id="alert-channel-filter"
            value={channelFilter}
            onChange={(event) => setChannelFilter(event.target.value)}
          >
            <option value="ALL">All channels</option>
            {channels.map((channel) => (
              <option key={channel} value={channel}>
                {channel}
              </option>
            ))}
          </select>
        </div>
      </section>

      {filteredAlerts.length > 0 ? (
        <section className="alerts-table-card">
          <div className="table-card__header">
            <div>
              <h2>Recent alerts</h2>
              <p>Latest alert records ordered by creation time.</p>
            </div>
            <span className="table-card__count">{filteredAlerts.length} items</span>
          </div>

          <div className="alerts-table">
            <div className="alerts-table__row alerts-table__row--head">
              <span>Alert</span>
              <span>Channel</span>
              <span>Status</span>
              <span>Created</span>
              <span>Incident</span>
            </div>

            {filteredAlerts.map((alert) => {
              const incident = incidentById[alert.incidentId]

              return (
                <div className="alerts-table__row" key={alert.alertId}>
                  <span>
                    <strong>{alert.title}</strong>
                    <small>{alert.message}</small>
                  </span>

                  <span>
                    <StatusBadge value={alert.channel} variant="status" />
                  </span>

                  <span>
                    <StatusBadge value={alert.status} variant="slo" />
                  </span>

                  <span>{formatDate(alert.createdAt)}</span>

                  <span>
                    <button
                      className="inline-link-button"
                      type="button"
                      disabled={!incident}
                      onClick={() => {
                        if (incident) {
                          onSelectIncident(incident)
                        }
                      }}
                    >
                      {getIncidentSummary(incident)}
                    </button>
                  </span>
                </div>
              )
            })}
          </div>
        </section>
      ) : (
        <div className="table-card">
          <div className="empty-state">
            <strong>No alerts match the current filters</strong>
            <span>Adjust the filters or trigger a new incident to create alerts.</span>
          </div>
        </div>
      )}
    </div>
  )
}
