package com.incidenthub.core.domain.metrics;

public enum OperationalMetricName {
    SIGNAL_PROCESSING_TASKS_TOTAL,
    SIGNAL_PROCESSING_TASKS_PENDING,
    SIGNAL_PROCESSING_TASKS_PROCESSED,
    SIGNAL_PROCESSING_TASKS_FAILED,
    SIGNAL_PROCESSING_SUCCESS_RATE,
    SIGNAL_PROCESSING_AVERAGE_LATENCY_MS,
    OLDEST_PENDING_TASK_AGE_SECONDS,

    INCIDENTS_OPEN,
    INCIDENTS_ACTIVE,
    INCIDENTS_RESOLVED,
    INCIDENTS_HIGH_OPEN,
    INCIDENTS_CRITICAL_OPEN,

    ALERTS_TOTAL,
    ALERTS_PENDING,
    ALERTS_SENT,
    ALERTS_FAILED,
    ALERT_DELIVERY_SUCCESS_RATE
}